### ISSUE TITLE
Unable to run the python inference.py

### ISSUE THREAD

**Issue by changruizhu96** [ragavsachdeva/CYWS-3D#1]
Thanks for the excellent work!
When I ran the command: 
`python inference.py --load_weights_from ./cyws-3d.ckpt
`
There was an error:
`/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/changrui/CYWS-3D/inference.py", line 59, in <module>
    CLI(main)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/changrui/CYWS-3D/inference.py", line 20, in main
    model = Model(configs, load_weights_from=load_weights_from)
  File "/home/changrui/CYWS-3D/modules/model.py", line 50, in __init__
    self.safely_load_state_dict(torch.load(load_weights_from))
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/changrui/anaconda3/envs/cyws3d/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.
`
It seems like there was some loading issue when it tried to load the pre-trained model. Now idea how to fix it, could you please help me?

**Comment by ragavsachdeva** [comment]
Hi! That's weird. Did you properly download and extract the pretrained weights?
```
cd CYWS-3D/
wget https://thor.robots.ox.ac.uk/cyws-3d/cyws-3d.ckpt.gz
gzip -d cyws-3d.ckpt.gz
python inference.py --load_weights_from ./cyws-3d.ckpt
```

**Comment by changruizhu96** [comment]
Thanks for your hints; I didn't extract it correctly. Now it works!
